AllCops:
  DisplayCopNames: true
  Exclude:
    - coverage/**/*
    - scrap/**/*
    - bin/*
  TargetRubyVersion: 2.4

Metrics/BlockNesting:
  Max: 2

Metrics/ClassLength:
  CountComments: false
  Max: 125

Metrics/PerceivedComplexity:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 8

Layout/LineLength:
  AllowURI: true
  Max: 165
  Exclude:
    - Gemfile*

Metrics/MethodLength:
  CountComments: false
  Max: 25
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - guanaco.gemspec

Metrics/ModuleLength:
  CountComments: false
  Max: 130
  Exclude:
    - spec/**/*.rb

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/AbcSize:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect:  'map'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Lambda:
  Enabled: false

Layout/SpaceAroundOperators:
  AllowForAlignment: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key

Style/SignalException:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
  
Naming/MethodParameterName:
  AllowedNames:
    - _
    - _e
    - e
    - to
    - tx
    - id

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ScriptPermission:
  Exclude:
  - check/**/*.rb

Style/FormatStringToken:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*.rb

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Naming/MethodName:
  Enabled: false

Lint/RescueException:
  Enabled: true

Lint/SuppressedException:
  Enabled: true
  Exclude:
    - Rakefile
