# frozen_string_literal: true

# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar'
  require 'com/fasterxml/jackson/core/jackson-annotations/2.10.3/jackson-annotations-2.10.3.jar'
  require 'com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.10.3/jackson-dataformat-yaml-2.10.3.jar'
  require 'io/netty/netty-common/4.1.48.Final/netty-common-4.1.48.Final.jar'
  require 'com/fasterxml/jackson/core/jackson-databind/2.10.3/jackson-databind-2.10.3.jar'
  require 'com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar'
  require 'org/javassist/javassist/3.22.0-GA/javassist-3.22.0-GA.jar'
  require 'io/netty/netty-tcnative/2.0.30.Final/netty-tcnative-2.0.30.Final-linux-x86_64.jar'
  require 'com/fasterxml/jackson/datatype/jackson-datatype-guava/2.10.3/jackson-datatype-guava-2.10.3.jar'
  require 'io/netty/netty-codec/4.1.48.Final/netty-codec-4.1.48.Final.jar'
  require 'com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.10.3/jackson-datatype-jdk8-2.10.3.jar'
  require 'io/ratpack/ratpack-test/1.8.0/ratpack-test-1.8.0.jar'
  require 'com/github/ben-manes/caffeine/caffeine/2.8.1/caffeine-2.8.1.jar'
  require 'com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar'
  require 'io/ratpack/ratpack-core/1.8.0/ratpack-core-1.8.0.jar'
  require 'io/netty/netty-codec-http/4.1.48.Final/netty-codec-http-4.1.48.Final.jar'
  require 'io/netty/netty-buffer/4.1.48.Final/netty-buffer-4.1.48.Final.jar'
  require 'io/netty/netty-transport/4.1.48.Final/netty-transport-4.1.48.Final.jar'
  require 'com/google/guava/guava/28.2-jre/guava-28.2-jre.jar'
  require 'com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar'
  require 'io/netty/netty-handler/4.1.48.Final/netty-handler-4.1.48.Final.jar'
  require 'com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar'
  require 'io/netty/netty-handler-proxy/4.1.48.Final/netty-handler-proxy-4.1.48.Final.jar'
  require 'org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar'
  require 'io/netty/netty-transport-native-epoll/4.1.48.Final/netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar'
  require 'io/netty/netty-transport-native-unix-common/4.1.48.Final/netty-transport-native-unix-common-4.1.48.Final.jar'
  require 'com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar'
  require 'org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar'
  require 'com/fasterxml/jackson/core/jackson-core/2.10.3/jackson-core-2.10.3.jar'
  require 'io/ratpack/ratpack-base/1.8.0/ratpack-base-1.8.0.jar'
  require 'io/ratpack/ratpack-exec/1.8.0/ratpack-exec-1.8.0.jar'
  require 'org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar'
  require 'org/checkerframework/checker-qual/3.1.0/checker-qual-3.1.0.jar'
  require 'org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar'
  require 'com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.10.3/jackson-datatype-jsr310-2.10.3.jar'
  require 'io/netty/netty-resolver/4.1.48.Final/netty-resolver-4.1.48.Final.jar'
  require 'io/netty/netty-codec-socks/4.1.48.Final/netty-codec-socks-4.1.48.Final.jar'
end

if defined? Jars
  require_jar 'com.google.code.findbugs', 'jsr305', '3.0.2'
  require_jar 'com.fasterxml.jackson.core', 'jackson-annotations', '2.10.3'
  require_jar 'com.fasterxml.jackson.dataformat', 'jackson-dataformat-yaml', '2.10.3'
  require_jar 'io.netty', 'netty-common', '4.1.48.Final'
  require_jar 'com.fasterxml.jackson.core', 'jackson-databind', '2.10.3'
  require_jar 'com.google.guava', 'listenablefuture', '9999.0-empty-to-avoid-conflict-with-guava'
  require_jar 'org.javassist', 'javassist', '3.22.0-GA'
  require_jar 'io.netty', 'netty-tcnative', 'linux-x86_64', '2.0.30.Final'
  require_jar 'com.fasterxml.jackson.datatype', 'jackson-datatype-guava', '2.10.3'
  require_jar 'io.netty', 'netty-codec', '4.1.48.Final'
  require_jar 'com.fasterxml.jackson.datatype', 'jackson-datatype-jdk8', '2.10.3'
  require_jar 'io.ratpack', 'ratpack-test', '1.8.0'
  require_jar 'com.github.ben-manes.caffeine', 'caffeine', '2.8.1'
  require_jar 'com.google.errorprone', 'error_prone_annotations', '2.3.4'
  require_jar 'io.ratpack', 'ratpack-core', '1.8.0'
  require_jar 'io.netty', 'netty-codec-http', '4.1.48.Final'
  require_jar 'io.netty', 'netty-buffer', '4.1.48.Final'
  require_jar 'io.netty', 'netty-transport', '4.1.48.Final'
  require_jar 'com.google.guava', 'guava', '28.2-jre'
  require_jar 'com.google.j2objc', 'j2objc-annotations', '1.3'
  require_jar 'io.netty', 'netty-handler', '4.1.48.Final'
  require_jar 'com.google.guava', 'failureaccess', '1.0.1'
  require_jar 'io.netty', 'netty-handler-proxy', '4.1.48.Final'
  require_jar 'org.slf4j', 'slf4j-simple', '1.7.30'
  require_jar 'io.netty', 'netty-transport-native-epoll', 'linux-x86_64', '4.1.48.Final'
  require_jar 'io.netty', 'netty-transport-native-unix-common', '4.1.48.Final'
  require_jar 'com.sun.activation', 'javax.activation', '1.2.0'
  require_jar 'org.reactivestreams', 'reactive-streams', '1.0.2'
  require_jar 'com.fasterxml.jackson.core', 'jackson-core', '2.10.3'
  require_jar 'io.ratpack', 'ratpack-base', '1.8.0'
  require_jar 'io.ratpack', 'ratpack-exec', '1.8.0'
  require_jar 'org.slf4j', 'slf4j-api', '1.7.30'
  require_jar 'org.checkerframework', 'checker-qual', '3.1.0'
  require_jar 'org.yaml', 'snakeyaml', '1.23'
  require_jar 'com.fasterxml.jackson.datatype', 'jackson-datatype-jsr310', '2.10.3'
  require_jar 'io.netty', 'netty-resolver', '4.1.48.Final'
  require_jar 'io.netty', 'netty-codec-socks', '4.1.48.Final'
end
